- name: Odoo
  hosts: all
  become: yes
  roles:
    - ansible-odoo
  vars:
    - odoo_version: 11.0
    - odoo_config_admin_passwd: admin
    - odoo_config_addons_path:
        - "/home/{{ odoo_user }}/server/odoo/addons"
        - "/home/{{ odoo_user }}/server/addons"
